@extends('auth.layout')

@section('title', 'Create account | Luvora')
@section('brand-heading', 'Your personal passage into island craft.')
@section('brand-copy', 'Create your Luvora account to keep your favorite finds, order history, and account details in one place.')

@section('content')
    <p class="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Join the society</p>
    <h2 class="mt-2 font-display text-4xl sm:text-5xl">Create your account</h2>
    <p class="mt-3 text-sm leading-6 text-slate-500">A few details to get your Luvora account started.</p>
    @if ($errors->any())<div role="alert" class="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{{ $errors->first() }}</div>@endif

    <form method="POST" action="{{ route('register') }}" class="mt-6 space-y-4">@csrf
        <div class="grid gap-4 sm:grid-cols-2">
            <label class="block"><span class="mb-2 block text-xs font-semibold text-slate-700">First name</span><input name="first_name" value="{{ old('first_name') }}" autocomplete="given-name" required class="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-blue-100" placeholder="First name">@error('first_name')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
            <label class="block"><span class="mb-2 block text-xs font-semibold text-slate-700">Last name</span><input name="last_name" value="{{ old('last_name') }}" autocomplete="family-name" required class="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-blue-100" placeholder="Last name">@error('last_name')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        </div>
        <label class="block"><span class="mb-2 block text-xs font-semibold text-slate-700">Email address</span><span class="relative block"><span class="material-symbols-outlined absolute left-3 top-3 text-lg text-slate-400">mail</span><input type="email" name="email" value="{{ old('email') }}" autocomplete="email" required class="w-full rounded-xl border border-slate-300 bg-slate-50 py-3 pl-11 pr-4 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-blue-100" placeholder="you@example.com"></span>@error('email')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block"><span class="mb-2 block text-xs font-semibold text-slate-700">Create password</span><span class="relative block"><span class="material-symbols-outlined absolute left-3 top-3 text-lg text-slate-400">key</span><input id="register-password" type="password" name="password" autocomplete="new-password" minlength="8" required class="w-full rounded-xl border border-slate-300 bg-slate-50 py-3 pl-11 pr-14 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-blue-100" placeholder="At least 8 characters"><button type="button" data-toggle-password="register-password" class="absolute right-3 top-2.5 text-slate-500" aria-label="Show password"><span class="material-symbols-outlined">visibility</span></button></span><span class="mt-2 block h-1 overflow-hidden rounded-full bg-slate-100"><span id="strength-bar" class="block h-full w-0 rounded-full bg-rose-500 transition-all"></span></span><span id="strength-label" class="mt-1 block text-[11px] text-slate-500">Use at least 8 characters.</span>@error('password')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block"><span class="mb-2 block text-xs font-semibold text-slate-700">Confirm password</span><input type="password" name="password_confirmation" autocomplete="new-password" required class="w-full rounded-xl border border-slate-300 bg-slate-50 px-4 py-3 text-sm outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-blue-100" placeholder="Enter password again"></label>
        <label class="flex items-start gap-3 text-xs leading-5 text-slate-600"><input type="checkbox" name="terms" value="1" required class="mt-1 accent-primary"><span>I agree to the Luvora terms of service and privacy policy.</span></label>@error('terms')<span class="block text-xs text-rose-700">{{ $message }}</span>@enderror
        <label class="flex items-start gap-3 text-xs leading-5 text-slate-500"><input type="checkbox" name="newsletter" value="1" class="mt-1 accent-primary"><span>Send me occasional news about new collections and island makers.</span></label>
        <button class="w-full rounded-full bg-ink px-6 py-3.5 text-sm font-semibold text-white transition hover:bg-primary">Create Luvora account</button>
    </form>
    <p class="mt-6 text-center text-sm text-slate-600">Already have an account? <a href="{{ route('login.show') }}" class="font-semibold text-primary hover:underline">Sign in</a></p>
    <script>document.querySelectorAll('[data-toggle-password]').forEach(button=>button.addEventListener('click',()=>{const input=document.getElementById(button.dataset.togglePassword);input.type=input.type==='password'?'text':'password'}));const pass=document.getElementById('register-password');pass.addEventListener('input',()=>{const v=pass.value;let score=(v.length>=8)+(v.length>=12)+(/[A-Z]/.test(v)&&/[a-z]/.test(v))+(/\d/.test(v)||/[^A-Za-z0-9]/.test(v));const bar=document.getElementById('strength-bar');bar.style.width=['0%','25%','50%','75%','100%'][score];bar.className='block h-full rounded-full transition-all '+(score<2?'bg-rose-500':score<4?'bg-amber-500':'bg-emerald-600');document.getElementById('strength-label').textContent=v.length?['Too weak','Weak','Fair','Good','Strong'][score]:'Use at least 8 characters.'});</script>
@endsection
