@extends('errors.layout')
@section('code','401 · Session expired')
@section('status-label','Luvora security gateway')
@section('icon','shield_lock')
@section('heading','Your Sanctuary Session Has Elapsed')
@section('message','For your privacy, this session has ended. Sign in again to continue to your account.')
@section('primary-label','Sign in again')
@section('primary-url',route('login.show'))
@section('primary-icon','login')
@section('secondary-label','Browse the shop')
@section('secondary-url',route('shop.index'))
