@extends('errors.layout')
@section('code','403 · Restricted access')
@section('status-label','Security protocols')
@section('icon','lock')
@section('heading','Access Reserved: Sovereign Chamber Restricted.')
@section('message','This page requires access that is not available to your account. If you believe you should be able to view it, contact the Luvora concierge team.')
@section('primary-label','Return to the shop')
@section('primary-url',route('shop.index'))
@section('primary-icon','storefront')
@section('secondary-label','Contact concierge')
