@extends('errors.layout')
@section('code','404 · Page not found')
@section('status-label','Luvora concierge gateway')
@section('icon','search_off')
@section('heading','This Couture Chamber Does Not Exist.')
@section('message','The page may have moved, the address may be incorrect, or the page may no longer be available.')
@section('primary-label','Return to the atelier home')
@section('primary-url',route('home'))
@section('primary-icon','home')
@section('secondary-label','Explore the shop')
@section('secondary-url',route('shop.index'))
