@extends('errors.layout')
@section('code','429 · Too many requests')
@section('status-label','Request limit')
@section('icon','hourglass_top')
@section('heading','Atelier Inquiries Exceeding Sanctuary Velocity.')
@section('message','We’ve received too many requests in a short time and have paused this action briefly. Please wait a moment before trying again.')
@section('primary-label','Try again')
@section('primary-url',url()->current())
@section('primary-icon','refresh')
@section('secondary-label','Return to Luvora')
