@extends('errors.layout')
@section('code','500 · Server error')
@section('status-label','Atelier system notice')
@section('icon','error')
@section('heading','Something Went Awry Within the Sovereign Atelier.')
@section('message','An unexpected error prevented us from completing your request. Please try again shortly.')
@section('primary-label','Return to the atelier')
@section('primary-url',route('home'))
@section('primary-icon','home')
@section('secondary-label','Contact concierge')
