@extends('errors.layout')
@section('code','503 · Service unavailable')
@section('status-label','Luvora security gateway')
@section('icon','engineering')
@section('heading','The Sovereign Atelier Is Undergoing Refined Curation.')
@section('message','Luvora is temporarily unavailable while service is restored. Please try again in a little while.')
@section('primary-label','Try again')
@section('primary-url',url()->current())
@section('primary-icon','refresh')
@section('secondary-label','Contact concierge')
