@extends('errors.layout')
@section('code','Offline')
@section('status-label','Connection notice')
@section('icon','wifi_off')
@section('heading','Your Connection to the Atelier Has Been Severed.')
@section('message','This page could not reach Luvora. Check your internet connection, then try again. Anything not yet saved may need to be submitted again.')
@section('primary-label','Try again')
@section('primary-url',url()->current())
@section('primary-icon','refresh')
@section('secondary-label','Return to Luvora')
