<footer class="mt-12 border-t border-slate-200 bg-white">
    <div class="mx-auto grid max-w-7xl gap-8 px-5 py-10 sm:grid-cols-2 lg:grid-cols-4 lg:px-8">
        <div><a href="{{ route('home') }}" class="inline-flex items-center" aria-label="Luvora home"><img src="{{ asset('images/logo.png') }}" alt="Luvora" class="h-10 w-auto"></a><p class="mt-3 max-w-xs text-xs leading-5 text-slate-500">Thoughtful fashion, local craft, and considered design from Sri Lanka.</p></div>
        <div><h2 class="text-xs font-semibold uppercase tracking-wider">Discover</h2><ul class="mt-3 space-y-2 text-xs text-slate-500"><li><a href="{{ route('shop.index') }}" class="hover:text-blue-700">Shop all</a></li><li><a href="{{ route('collections.index') }}" class="hover:text-blue-700">Collections</a></li><li><a href="{{ route('gift-guide') }}" class="hover:text-blue-700">Gift guide</a></li><li><a href="{{ route('journal.index') }}" class="hover:text-blue-700">Journal</a></li><li><a href="{{ route('stores.index') }}" class="hover:text-blue-700">Store locations</a></li></ul></div>
        <div><h2 class="text-xs font-semibold uppercase tracking-wider">Your Luvora</h2><ul class="mt-3 space-y-2 text-xs text-slate-500"><li><a href="{{ route('account.dashboard') }}" class="hover:text-blue-700">Account</a></li><li><a href="{{ route('account.orders.index') }}" class="hover:text-blue-700">Orders</a></li><li><a href="{{ route('wishlist.index') }}" class="hover:text-blue-700">Wishlist</a></li><li><a href="{{ route('cart.index') }}" class="hover:text-blue-700">Shopping bag</a></li><li><a href="{{ route('recently-viewed') }}" class="hover:text-blue-700">Recently viewed</a></li></ul></div>
        <div><h2 class="text-xs font-semibold uppercase tracking-wider">Help &amp; information</h2><ul class="mt-3 space-y-2 text-xs text-slate-500"><li><a href="{{ route('customer-care.contact') }}" class="hover:text-blue-700">Contact customer care</a></li><li><a href="{{ route('customer-care.size-guide') }}" class="hover:text-blue-700">Size guide</a></li><li><a href="{{ route('customer-care.shipping') }}" class="hover:text-blue-700">Shipping information</a></li><li><a href="{{ route('customer-care.returns') }}" class="hover:text-blue-700">Returns &amp; exchanges</a></li><li><a href="{{ route('sitemap') }}" class="hover:text-blue-700">Sitemap</a></li></ul></div>
    </div>
    <div class="border-t border-slate-100"><div class="mx-auto flex max-w-7xl flex-wrap justify-between gap-3 px-5 py-4 text-[11px] text-slate-400 lg:px-8"><span>© {{ date('Y') }} Luvora</span><div class="flex gap-4"><a href="{{ route('legal.privacy') }}" class="hover:text-blue-700">Privacy</a><a href="{{ route('legal.terms') }}" class="hover:text-blue-700">Terms</a><a href="{{ route('legal.cookies') }}" class="hover:text-blue-700">Cookies</a></div></div></div>
</footer>
