<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{{ $page['title'] }} | Luvora</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,400;6..96,500;6..96,600&family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#f7f9fb] font-['Plus_Jakarta_Sans'] text-[#191c1e]">@include('partials.site-header')
@php
    $breadcrumbs = match($page['eyebrow']) {
        'About Luvora' => ['About Luvora' => route('about')],
        'Legal & policies' => ['Policies' => route('legal.privacy')],
        'Customer care' => ['Customer care' => route('help')],
        default => [],
    };
    $helpLinks = [
        ['Orders & tracking','View order status and tracking details.','customer-care.orders','receipt_long'],
        ['Payments','Learn about payment options.','customer-care.payment','payments'],
        ['Delivery','Delivery information and coverage.','customer-care.delivery','local_shipping'],
        ['Returns','Review return and exchange information.','customer-care.returns','assignment_return'],
    ];
    $aboutLinks = [
        ['Our heritage','about.heritage'],['Artisan guild','about.artisans'],['Craftsmanship','about.craftsmanship'],['Sustainability','about.sustainability'],['Collections story','about.collections'],['Authenticity','authenticity'],
    ];
@endphp
<main class="mx-auto max-w-7xl px-5 py-8 sm:py-12 lg:px-8"><div class="mb-7 text-xs text-slate-500"><a href="{{ route('home') }}" class="hover:text-blue-700">Home</a>@foreach($breadcrumbs as $label=>$url)<span class="mx-2">/</span><a href="{{ $url }}" class="hover:text-blue-700">{{ $label }}</a>@endforeach<span class="mx-2">/</span><span class="text-slate-900">{{ $page['title'] }}</span></div>
<section class="relative overflow-hidden rounded-3xl bg-[#10283d] px-6 py-10 text-white sm:px-10 sm:py-14"><div class="absolute -right-10 -top-24 h-72 w-72 rounded-full bg-sky-300/20 blur-3xl"></div><div class="relative max-w-3xl"><p class="text-[10px] font-semibold uppercase tracking-[0.25em] text-sky-200">{{ $page['eyebrow'] }}</p><h1 class="mt-3 font-['Bodoni_Moda'] text-4xl sm:text-6xl">{{ $page['title'] }}</h1><p class="mt-4 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base">{{ $page['intro'] }}</p></div></section>
@if(session('form_notice'))<div role="status" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">{{ session('form_notice') }}</div>@endif
@if(session('newsletter_notice'))<div role="status" class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">{{ session('newsletter_notice') }}</div>@endif
@if($errors->any())<div role="alert" class="mt-5 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{{ $errors->first() }}</div>@endif

@if($page['type']==='contact')
    <div class="mt-7 grid items-start gap-6 lg:grid-cols-12"><section class="rounded-2xl bg-white p-6 shadow-sm sm:p-8 lg:col-span-7"><h2 class="font-['Bodoni_Moda'] text-2xl">Send a message to customer care</h2><p class="mt-2 text-xs leading-5 text-slate-500">This form is a preview and will not transmit or save your message until a support service is connected.</p><form method="POST" action="{{ route('customer-care.contact.submit') }}" class="mt-6 grid gap-4 sm:grid-cols-2">@csrf
        @foreach([['name','Full name','text'],['email','Email address','email'],['phone','Phone number (optional)','tel']] as [$field,$label,$type])<label class="block {{ $field==='phone'?'sm:col-span-2':'' }}"><span class="mb-1.5 block text-xs font-semibold text-slate-600">{{ $label }}</span><input type="{{ $type }}" name="{{ $field }}" value="{{ old($field) }}" @required($field!=='phone') class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm focus:border-blue-700 focus:outline-none">@error($field)<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>@endforeach
        <label class="block sm:col-span-2"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Subject</span><select name="subject" required class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Choose a topic</option>@foreach(['Product question','Order help','Delivery','Payment','Returns or exchanges','Account support','Other'] as $subject)<option @selected(old('subject')===$subject)>{{ $subject }}</option>@endforeach</select>@error('subject')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <label class="block sm:col-span-2"><span class="mb-1.5 block text-xs font-semibold text-slate-600">Message</span><textarea name="message" rows="5" required maxlength="3000" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm focus:border-blue-700 focus:outline-none">{{ old('message') }}</textarea>@error('message')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>
        <fieldset class="sm:col-span-2"><legend class="mb-2 text-xs font-semibold text-slate-600">Preferred contact channel</legend><div class="flex flex-wrap gap-4">@foreach(['email'=>'Email','phone'=>'Phone','whatsapp'=>'WhatsApp'] as $value=>$label)<label class="flex items-center gap-2 text-xs"><input type="radio" name="preferred_channel" value="{{ $value }}" @checked(old('preferred_channel','email')===$value) class="accent-blue-700">{{ $label }}</label>@endforeach</div>@error('preferred_channel')<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</fieldset>
        <button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white hover:bg-blue-800 sm:col-span-2">Check message form</button></form></section>
        <aside class="space-y-4 lg:col-span-5"><div class="rounded-2xl bg-white p-6 shadow-sm"><span class="material-symbols-outlined text-2xl text-blue-700">storefront</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">Luvora customer care</h2><p class="mt-2 text-sm leading-6 text-slate-600">Verified phone, email, opening hours, and physical address details are not configured in this application. No unverified contact details are shown here.</p></div><div class="rounded-2xl bg-slate-100 p-6"><h3 class="font-semibold">Order assistance</h3><p class="mt-2 text-xs leading-5 text-slate-600">Sign in to view the order information currently available from your account.</p><a href="{{ route('account.orders.index') }}" class="mt-4 inline-block text-sm font-semibold text-blue-700 hover:underline">Go to my orders →</a></div><div class="rounded-2xl bg-slate-100 p-6"><h3 class="font-semibold">Concierge</h3><p class="mt-2 text-xs leading-5 text-slate-600">Learn what customer concierge support covers.</p><a href="{{ route('customer-care.concierge') }}" class="mt-4 inline-block text-sm font-semibold text-blue-700 hover:underline">View concierge information →</a></div></aside></div>
@elseif($page['type']==='report-issue')
    <div class="mt-7 max-w-3xl rounded-2xl bg-white p-6 shadow-sm sm:p-8"><p class="mb-5 rounded-lg bg-amber-50 p-4 text-xs leading-5 text-amber-900">The issue report will not be sent until a support ticket service is connected.</p><form method="POST" action="{{ route('customer-care.report-issue.submit') }}" class="space-y-4">@csrf<label class="block text-xs font-semibold">Email address<input type="email" name="email" value="{{ old('email') }}" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm"></label>@error('email')<p class="text-xs text-rose-700">{{ $message }}</p>@enderror<label class="block text-xs font-semibold">Order number (optional)<input name="order_number" value="{{ old('order_number') }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm"></label><label class="block text-xs font-semibold">Issue category<select name="category" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm"><option value="">Choose a category</option>@foreach(['Website','Product','Order','Delivery','Payment','Account','Other'] as $category)<option>{{ $category }}</option>@endforeach</select></label><label class="block text-xs font-semibold">What happened?<textarea name="details" required rows="5" maxlength="3000" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm">{{ old('details') }}</textarea></label>@error('details')<p class="text-xs text-rose-700">{{ $message }}</p>@enderror<button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Check issue report</button></form></div>
@elseif($page['type']==='newsletter')
    <div class="mt-7 grid gap-6 lg:grid-cols-2"><section class="rounded-2xl bg-white p-6 shadow-sm sm:p-8"><span class="material-symbols-outlined text-3xl text-blue-700">mail</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">Join the Luvora letter</h2><p class="mt-2 text-sm leading-6 text-slate-500">Occasional notes about collections and makers. Subscription is not active until the newsletter service is connected.</p><form method="POST" action="{{ route('newsletter.subscribe') }}" class="mt-6 space-y-4">@csrf<label class="block text-xs font-semibold">Email address<input type="email" name="email" value="{{ old('email') }}" required autocomplete="email" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm"></label>@error('email')<p class="text-xs text-rose-700">{{ $message }}</p>@enderror<label class="flex items-start gap-3 text-xs leading-5 text-slate-600"><input type="checkbox" name="consent" value="1" required class="mt-1 accent-blue-700"><span>I agree to receive newsletter emails and understand I can unsubscribe later.</span></label><button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Continue</button></form></section><aside class="rounded-2xl bg-slate-100 p-6"><h3 class="font-semibold">Your inbox, your choice</h3><p class="mt-2 text-sm leading-6 text-slate-600">Your email is not retained by this preview page. Newsletter subscriptions will be enabled when a mailing-list provider is configured.</p></aside></div>
@elseif($page['type']==='confirmation')
    <section class="mx-auto mt-7 max-w-2xl rounded-2xl bg-white p-8 text-center shadow-sm"><span class="material-symbols-outlined text-5xl text-amber-600">info</span><h2 class="mt-4 font-['Bodoni_Moda'] text-3xl">Subscription not confirmed</h2><p class="mt-3 text-sm leading-6 text-slate-600">{{ session('newsletter_notice') ?? 'No newsletter subscription has been recorded.' }}</p><a href="{{ route('newsletter') }}" class="mt-6 inline-flex rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Back to newsletter</a></section>
@elseif($page['type']==='gift-card-balance')
    <section class="mt-7 max-w-2xl rounded-2xl bg-white p-6 shadow-sm sm:p-8"><p class="mb-5 rounded-lg bg-amber-50 p-4 text-xs leading-5 text-amber-900">Balance lookup is not connected. Gift card codes are not stored or checked on this page.</p><form method="POST" action="{{ route('gift-cards.check-balance') }}" class="space-y-4">@csrf<label class="block text-xs font-semibold">Gift card code<input name="gift_card_code" required autocomplete="off" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-3 text-sm" placeholder="Enter card code"></label>@error('gift_card_code')<span class="text-xs text-rose-700">{{ $message }}</span>@enderror<button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Check availability</button></form></section>
@elseif($page['type']==='faq')
    <section class="mt-7 grid gap-6 lg:grid-cols-12"><div class="lg:col-span-8"><label class="block"><span class="sr-only">Search help questions</span><input id="faq-search" type="search" placeholder="Search a question..." class="w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm shadow-sm"></label><div class="mt-4 space-y-3">@foreach($page['sections'] as $section)<details data-faq-item class="rounded-xl bg-white p-5 shadow-sm"><summary class="cursor-pointer list-none pr-8 font-semibold">{{ $section['title'] }}</summary><p class="mt-3 text-sm leading-6 text-slate-600">{{ $section['body'] }}</p></details>@endforeach<p id="faq-empty" class="hidden rounded-xl bg-white p-6 text-center text-sm text-slate-500">No matching questions found.</p></div></div><aside class="rounded-2xl bg-white p-5 shadow-sm lg:col-span-4"><h2 class="font-['Bodoni_Moda'] text-2xl">Help by topic</h2><div class="mt-4 space-y-2">@foreach($helpLinks as [$label,$description,$route,$icon])<a href="{{ route($route) }}" class="flex gap-3 rounded-xl bg-slate-50 p-3 hover:bg-blue-50"><span class="material-symbols-outlined text-blue-700">{{ $icon }}</span><span><strong class="block text-sm">{{ $label }}</strong><span class="mt-1 block text-xs text-slate-500">{{ $description }}</span></span></a>@endforeach</div></aside></section><script>const faqSearch=document.getElementById('faq-search');faqSearch.addEventListener('input',()=>{const q=faqSearch.value.toLowerCase();let shown=0;document.querySelectorAll('[data-faq-item]').forEach(item=>{const match=item.innerText.toLowerCase().includes(q);item.classList.toggle('hidden',!match);shown+=match});document.getElementById('faq-empty').classList.toggle('hidden',shown>0)});</script>
@elseif($page['type']==='help')
    <section class="mt-7 grid gap-4 sm:grid-cols-2">@foreach($helpLinks as [$label,$description,$route,$icon])<a href="{{ route($route) }}" class="rounded-2xl bg-white p-6 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span class="material-symbols-outlined text-2xl text-blue-700">{{ $icon }}</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">{{ $label }}</h2><p class="mt-2 text-sm leading-6 text-slate-500">{{ $description }}</p><span class="mt-4 inline-block text-sm font-semibold text-blue-700">View information →</span></a>@endforeach<a href="{{ route('faq') }}" class="rounded-2xl bg-white p-6 shadow-sm"><span class="material-symbols-outlined text-2xl text-blue-700">quiz</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">Frequently asked questions</h2><p class="mt-2 text-sm text-slate-500">Browse common customer questions.</p></a><a href="{{ route('customer-care.contact') }}" class="rounded-2xl bg-white p-6 shadow-sm"><span class="material-symbols-outlined text-2xl text-blue-700">support_agent</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">Contact customer care</h2><p class="mt-2 text-sm text-slate-500">Open the message form preview.</p></a></section>
@elseif($page['type']==='about')
    <section class="mt-7 grid gap-7 lg:grid-cols-12"><div class="space-y-4 lg:col-span-8">@foreach($page['sections'] as $section)<article class="rounded-2xl bg-white p-6 shadow-sm sm:p-8"><p class="text-[10px] font-semibold uppercase tracking-[0.2em] text-blue-700">Luvora</p><h2 class="mt-2 font-['Bodoni_Moda'] text-2xl sm:text-3xl">{{ $section['title'] }}</h2><p class="mt-3 text-sm leading-7 text-slate-600">{{ $section['body'] }}</p></article>@endforeach</div><aside class="h-fit rounded-2xl bg-slate-100 p-6 lg:col-span-4"><h2 class="font-['Bodoni_Moda'] text-2xl">Explore our story</h2><div class="mt-4 space-y-1">@foreach($aboutLinks as [$label,$route])<a href="{{ route($route) }}" class="flex items-center justify-between border-b border-slate-200 py-3 text-sm hover:text-blue-700"><span>{{ $label }}</span><span>→</span></a>@endforeach</div><a href="{{ route('shop.index') }}" class="mt-6 inline-flex rounded-full bg-[#005baf] px-5 py-3 text-sm font-semibold text-white">Explore the shop</a></aside></section>
@elseif($page['type']==='offers')
    <section class="mt-7 rounded-2xl bg-white px-6 py-14 text-center shadow-sm"><span class="material-symbols-outlined text-4xl text-slate-400">sell</span><h2 class="mt-4 font-['Bodoni_Moda'] text-3xl">No current offers listed</h2><p class="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">A promotions feed is not connected, so this page is not showing unverified discounts.</p><a href="{{ route('shop.index') }}" class="mt-6 inline-flex rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Browse the shop</a></section>
@else
    @if($page['type']==='legal')<div class="mt-7 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-amber-900">Draft notice: final policy language has not been supplied for this storefront. This page is not a substitute for the approved Luvora policy.</div>@endif
    <div class="mt-7 grid gap-5 md:grid-cols-2">@foreach($page['sections'] as $section)<article class="rounded-2xl bg-white p-6 shadow-sm"><span class="material-symbols-outlined text-2xl text-blue-700">{{ $page['type']==='legal'?'policy':'info' }}</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">{{ $section['title'] }}</h2><p class="mt-2 text-sm leading-6 text-slate-600">{{ $section['body'] }}</p></article>@endforeach</div>
    @if($page['type']==='gift-cards')<div class="mt-6 flex flex-wrap gap-3"><a href="{{ route('gift-cards.balance') }}" class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white">Check gift card balance</a><a href="{{ route('customer-care.contact') }}" class="rounded-full border border-slate-300 px-6 py-3 text-sm font-semibold">Ask customer care</a></div>@endif
    @if(in_array($page['type'],['loyalty','rewards','referrals']))<div class="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">Programme features are not connected. No points, member status, referral code, or rewards are being created or estimated.</div>@endif
@endif
<section class="mt-8 flex flex-col justify-between gap-4 rounded-2xl bg-slate-100 p-6 sm:flex-row sm:items-center"><div><h2 class="font-['Bodoni_Moda'] text-2xl">Continue exploring Luvora</h2><p class="mt-1 text-sm text-slate-600">Browse the catalogue or get help with an order.</p></div><div class="flex flex-wrap gap-3"><a href="{{ route('shop.index') }}" class="rounded-full bg-[#005baf] px-5 py-2.5 text-sm font-semibold text-white">Shop</a><a href="{{ route('customer-care.orders') }}" class="rounded-full border border-slate-300 bg-white px-5 py-2.5 text-sm font-semibold">Order help</a></div></section>
</main>@include('partials.site-footer')</body></html>
