@extends('account.layout')
@section('title','Edit Profile | Luvora')
@section('content')
@php $profile=session('account.profile',[]); $first=$profile['first_name']??data_get($user,'first_name')??data_get($user,'firstName')??''; $last=$profile['last_name']??data_get($user,'last_name')??data_get($user,'lastName')??''; $email=data_get($user,'email')??data_get($user,'Email')??''; @endphp
<div class="mb-7"><p class="text-xs font-semibold uppercase tracking-[0.2em] text-blue-700">Patron profile</p><h1 class="mt-2 font-['Bodoni_Moda'] text-4xl sm:text-5xl">Edit your details</h1><p class="mt-2 text-sm text-slate-500">Update your profile and style preferences.</p></div>
<div class="mb-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900">Profile changes are stored in this Laravel session only. The current account API does not provide a profile update endpoint.</div>
<form method="POST" action="{{ route('account.profile.update') }}" class="space-y-6 rounded-2xl bg-white p-6 shadow-sm sm:p-8">@csrf @method('PUT')
<section><h2 class="font-['Bodoni_Moda'] text-2xl">Personal information</h2><div class="mt-4 grid gap-4 sm:grid-cols-2">@foreach([['first_name','First name',$first],['last_name','Last name',$last],['display_name','Preferred display name',$profile['display_name']??data_get($user,'display_name')??data_get($user,'displayName')??'']] as [$field,$label,$value])<label><span class="mb-1.5 block text-xs font-semibold text-slate-600">{{ $label }}</span><input name="{{ $field }}" value="{{ old($field,$value) }}" @required(in_array($field,['first_name','last_name'])) class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm focus:border-blue-700 focus:outline-none">@error($field)<span class="mt-1 block text-xs text-rose-700">{{ $message }}</span>@enderror</label>@endforeach<label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Date of birth</span><input type="date" name="date_of_birth" value="{{ old('date_of_birth',$profile['date_of_birth']??data_get($user,'date_of_birth')??'') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Wardrobe category</span><select name="wardrobe_category" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"><option value="">Select</option>@foreach(['women'=>'Women','men'=>'Men','unisex'=>'Unisex'] as $key=>$label)<option value="{{ $key }}" @selected(old('wardrobe_category',$profile['wardrobe_category']??'')===$key)>{{ $label }}</option>@endforeach</select></label></div></section>
<section class="border-t border-slate-100 pt-5"><h2 class="font-['Bodoni_Moda'] text-2xl">Contact channels</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Email address</span><input value="{{ $email }}" readonly class="w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm text-slate-500"><span class="mt-1 block text-[11px] text-slate-400">Email changes require verification and are not available here.</span></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Mobile / WhatsApp</span><input name="phone" value="{{ old('phone',$profile['phone']??data_get($user,'phone')??data_get($user,'phoneNumber')??'') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Secondary phone</span><input name="secondary_phone" value="{{ old('secondary_phone',$profile['secondary_phone']??'') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Preferred contact</span><select name="preferred_channel" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm">@foreach(['email'=>'Email','phone'=>'Phone','whatsapp'=>'WhatsApp'] as $key=>$label)<option value="{{ $key }}" @selected(old('preferred_channel',$profile['preferred_channel']??'email')===$key)>{{ $label }}</option>@endforeach</select></label></div></section>
<section class="border-t border-slate-100 pt-5"><h2 class="font-['Bodoni_Moda'] text-2xl">Atelier preferences</h2><div class="mt-4 grid gap-4 sm:grid-cols-2"><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Standard size</span><input name="standard_size" value="{{ old('standard_size',$profile['standard_size']??'') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" placeholder="e.g. M"></label><label><span class="mb-1.5 block text-xs font-semibold text-slate-600">Alteration preferences</span><input name="alteration_preference" value="{{ old('alteration_preference',$profile['alteration_preference']??'') }}" class="w-full rounded-lg border border-slate-300 px-3 py-2.5 text-sm" placeholder="Optional"></label></div><p class="mb-2 mt-4 text-xs font-semibold text-slate-600">Preferred fabrics</p><div class="flex flex-wrap gap-3">@foreach(['Handloom cotton','Linen','Raw silk','Batik','Lace'] as $fabric)<label class="flex items-center gap-2 rounded-full bg-slate-50 px-3 py-2 text-xs"><input type="checkbox" name="preferred_fabrics[]" value="{{ $fabric }}" @checked(in_array($fabric,old('preferred_fabrics',$profile['preferred_fabrics']??[]))) class="accent-blue-700">{{ $fabric }}</label>@endforeach</div></section>
<div class="flex flex-wrap justify-between gap-3 border-t border-slate-100 pt-5"><a href="{{ route('account.profile') }}" class="rounded-full border border-slate-300 px-5 py-3 text-sm font-semibold">Cancel</a><button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white hover:bg-blue-800">Save profile for this session</button></div>
</form>@endsection
