<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Track Order | Luvora</title><link rel="preconnect" href="https://fonts.googleapis.com"><link href="https://fonts.googleapis.com/css2?family=Bodoni+Moda:opsz,wght@6..96,400;6..96,500&family=Inter:wght@400;500;600;700&family=Plus+Jakarta+Sans:wght@400;500;600&display=swap" rel="stylesheet"><link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet"><script src="https://cdn.tailwindcss.com"></script></head>
<body class="min-h-screen bg-[#f7f9fb] font-['Plus_Jakarta_Sans'] text-[#191c1e]"><header class="border-b border-slate-200 bg-white"><div class="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><a href="{{ route('home') }}" class="flex items-center gap-3"><img src="{{ asset('images/logo.png') }}" alt="Luvora" class="h-10 w-auto"></a><nav class="flex gap-4 text-sm"><a href="{{ route('account.orders.index') }}" class="text-slate-600 hover:text-blue-700">Order history</a><a href="{{ route('shop.index') }}" class="text-slate-600 hover:text-blue-700">Shop</a></nav></div></header>
<main class="mx-auto max-w-7xl px-5 py-10"><div class="mb-7 text-sm text-slate-500"><a href="{{ route('home') }}" class="hover:text-blue-700">Home</a><span class="mx-2">/</span><a href="{{ route('account.orders.index') }}" class="hover:text-blue-700">Orders</a><span class="mx-2">/</span><span class="text-slate-900">Track order</span></div>
    @if (empty($order))<section class="mx-auto max-w-2xl rounded-2xl bg-white p-7 text-center shadow-sm sm:p-10"><span class="material-symbols-outlined text-4xl text-blue-700">local_shipping</span><p class="mt-4 text-xs font-semibold uppercase tracking-[0.2em] text-blue-700">Luvora delivery</p><h1 class="mt-2 font-['Bodoni_Moda'] text-4xl">Track your order</h1><p class="mt-3 text-sm leading-6 text-slate-500">Enter an order number from your account to see the latest order details.</p><form action="{{ route('orders.track') }}" method="GET" class="mt-7 flex flex-col gap-3 sm:flex-row"><input name="orderNumber" required placeholder="Order number" class="min-w-0 flex-1 rounded-full border border-slate-300 px-5 py-3 text-sm outline-none focus:border-blue-700"><button class="rounded-full bg-[#005baf] px-6 py-3 text-sm font-semibold text-white hover:bg-blue-800">Find order</button></form>
        @if ($ordersUnavailable)<p class="mt-5 rounded-lg bg-amber-50 p-3 text-left text-xs text-amber-900">The order service is temporarily unavailable. Please try again later.</p>@elseif(!empty($orders))<div class="mt-7 border-t border-slate-100 pt-5 text-left"><p class="mb-3 text-xs font-semibold uppercase tracking-wider text-slate-500">Recent orders</p><div class="space-y-2">@foreach($orders as $recent)@php $key=data_get($recent,'orderNumber')??data_get($recent,'OrderNumber')??data_get($recent,'id')??data_get($recent,'Id'); @endphp@if($key)<a href="{{ route('orders.track.show',$key) }}" class="flex items-center justify-between rounded-lg bg-slate-50 p-3 text-sm hover:bg-blue-50"><span>Order #{{ $key }}</span><span class="text-xs text-blue-700">View tracking →</span></a>@endif @endforeach</div></div>@endif
    </section>@else
        @php $number=data_get($order,'orderNumber')??data_get($order,'OrderNumber')??data_get($order,'reference')??$orderKey; $status=data_get($order,'status')??data_get($order,'Status')??'Status unavailable'; $items=data_get($order,'items')??data_get($order,'Items')??[]; $items=is_array($items)?$items:[]; @endphp
        <div class="mb-6 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-blue-700">Order tracking</p><h1 class="mt-2 font-['Bodoni_Moda'] text-4xl sm:text-5xl">Order #{{ $number }}</h1><p class="mt-2 text-sm text-slate-500">Current status: <strong class="text-slate-900">{{ $status }}</strong></p></div><a href="{{ route('account.orders.show',$orderKey) }}" class="text-sm font-semibold text-blue-700 hover:underline">View order details</a></div>
        <div class="grid items-start gap-6 lg:grid-cols-12">
            <section class="space-y-5 lg:col-span-8"><div class="relative flex min-h-72 items-center justify-center overflow-hidden rounded-2xl border border-slate-700 bg-slate-900 p-8 text-center text-white"><div class="absolute inset-0 opacity-20" style="background-image:linear-gradient(rgba(255,255,255,.18) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.18) 1px,transparent 1px);background-size:36px 36px"></div><div class="relative max-w-md"><span class="material-symbols-outlined text-4xl text-sky-300">location_searching</span><h2 class="mt-3 font-['Bodoni_Moda'] text-2xl">Live map unavailable</h2><p class="mt-2 text-sm leading-6 text-slate-300">Vehicle location and route updates will appear here when the delivery tracking service provides them. This page does not simulate a live GPS feed.</p></div></div>
            <div class="rounded-2xl bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-['Bodoni_Moda'] text-2xl">Delivery milestones</h2><span class="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">From order status</span></div><ol class="mt-6 space-y-5">@foreach(['Order received','Preparing your order','Dispatched','Delivered'] as $index=>$milestone)<li class="flex items-start gap-3"><span class="flex h-7 w-7 shrink-0 items-center justify-center rounded-full {{ $index===0 ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-400' }} text-xs font-bold">{{ $index===0?'✓':$index+1 }}</span><div><p class="text-sm font-semibold">{{ $milestone }}</p>@if($index===0)<p class="mt-1 text-xs text-slate-500">Order status reported: {{ $status }}</p>@else<p class="mt-1 text-xs text-slate-400">Waiting for an update from the order service</p>@endif</div></li>@endforeach</ol></div></section>
            <aside class="space-y-5 lg:col-span-4"><div class="rounded-2xl bg-white p-6 shadow-sm"><h2 class="font-['Bodoni_Moda'] text-2xl">Order contents</h2>@forelse($items as $item)@php $name=data_get($item,'product.name')??data_get($item,'productName')??data_get($item,'name')??'Luvora creation'; @endphp<div class="border-b border-slate-100 py-3 text-sm"><p class="font-medium">{{ $name }}</p><p class="mt-1 text-xs text-slate-500">Quantity: {{ data_get($item,'quantity')??data_get($item,'Quantity')??1 }}</p></div>@empty<p class="mt-4 text-sm text-slate-500">Item details are not available for this order.</p>@endforelse</div><div class="rounded-2xl bg-slate-100 p-5"><h3 class="font-semibold">Need assistance?</h3><p class="mt-2 text-xs leading-5 text-slate-600">For delivery questions, contact Luvora customer care with your order number.</p><a href="{{ route('account.orders.index') }}" class="mt-4 inline-block text-sm font-semibold text-blue-700 hover:underline">Return to order history</a></div></aside>
        </div>
    @endif
</main></body></html>
